#ifndef XG_RENDER_ROUTE_DESCRIPTOR_H
#define XG_RENDER_ROUTE_DESCRIPTOR_H

#include <stdint.h>

typedef enum XgRenderHookRouteKind {
    XG_RENDER_HOOK_ROUTE_NONE = 0,
    XG_RENDER_HOOK_ROUTE_CANONICAL_ENTRY,
    XG_RENDER_HOOK_ROUTE_CANONICAL_CAPTURE,
    XG_RENDER_HOOK_ROUTE_CANONICAL_RETURN,
    XG_RENDER_HOOK_ROUTE_UI_DRAW_OT,
} XgRenderHookRouteKind;

typedef struct XgRenderHookRouteDescriptor {
    XgRenderHookRouteKind kind;
    uint32_t hook_type;
    uint32_t pc;
    uint32_t instruction_word;
} XgRenderHookRouteDescriptor;

typedef enum XgRenderCutoverModule {
    XG_RENDER_CUTOVER_MODULE_PREAMBLE = 0,
    XG_RENDER_CUTOVER_MODULE_F4,
    XG_RENDER_CUTOVER_MODULE_OVERLAY_ADD_PRIM,
    XG_RENDER_CUTOVER_MODULE_RESIDENT_LINE,
    XG_RENDER_CUTOVER_MODULE_RESIDUAL,
    XG_RENDER_CUTOVER_MODULE_OVERLAY,
    XG_RENDER_CUTOVER_MODULE_WORLD,
    XG_RENDER_CUTOVER_MODULE_MODEL_PRE_FIELD,
    XG_RENDER_CUTOVER_MODULE_FIELD_SPRITE,
    XG_RENDER_CUTOVER_MODULE_OVERLAY_FIELD_MATERIAL,
    XG_RENDER_CUTOVER_MODULE_MODEL_POST_FIELD,
    XG_RENDER_CUTOVER_MODULE_PROJECTED,
    XG_RENDER_CUTOVER_MODULE_VARIANT,
    XG_RENDER_CUTOVER_MODULE_FIELD_CHARACTER,
} XgRenderCutoverModule;

typedef enum XgRenderCutoverAction {
    XG_CUTOVER_ROUTE_ONLY = 0,
    XG_CUTOVER_F4_FIXED_2A,
    XG_CUTOVER_F4_BATTLE_FADER,
    XG_CUTOVER_F4_PROJECTED_2A,
    XG_CUTOVER_F4_OBSERVE_2A_OT,
    XG_CUTOVER_RESIDUAL_CLEAR_TILE,
    XG_CUTOVER_RESIDUAL_FULLSCREEN_TILE,
    XG_CUTOVER_RESIDUAL_FADE_TILES,
    XG_CUTOVER_MODEL_FT4_TEMPLATE,
    XG_CUTOVER_MODEL_FT3_TEMPLATE,
    XG_CUTOVER_MODEL_FT3_LINK_CAPTURE,
    XG_CUTOVER_MODEL_FT3_LINK_FINISH,
    XG_CUTOVER_MODEL_FT4_GUEST_AVERAGE,
    XG_CUTOVER_MODEL_FT3_GUEST,
    XG_CUTOVER_MODEL_FT4_GUEST_FARTHEST,
    XG_CUTOVER_SPRITE_WRAPPER_BEGIN,
    XG_CUTOVER_SPRITE_BEGIN,
    XG_CUTOVER_SPRITE_GEOMETRY,
    XG_CUTOVER_SPRITE_MATERIAL,
    XG_CUTOVER_SPRITE_WRAPPER_END,
    XG_CUTOVER_SPRITE_END,
    XG_CUTOVER_MODEL_BEGIN,
    XG_CUTOVER_MODEL_FT4_SEAM,
    XG_CUTOVER_MODEL_FT3_SEAM,
    XG_CUTOVER_MODEL_FINISH,
    XG_CUTOVER_MODEL_END,
    XG_CUTOVER_PROJECTED_INITIALIZER_BEGIN,
    XG_CUTOVER_PROJECTED_INITIALIZER_COMMIT,
    XG_CUTOVER_PROJECTED_NATIVE,
} XgRenderCutoverAction;

typedef struct XgRenderCutoverRouteDescriptor {
    XgRenderCutoverModule module;
    uint32_t action;
    uint32_t pc;
    uint32_t instruction_word;
    uint32_t continuation;
} XgRenderCutoverRouteDescriptor;

#endif
