schema = "xenogears.native-render-replay/v3"
complete = true
vblank_budget = 1083
record_on_close = true

[[vblank]]
repeat = 587
p1_connected = true
p1_mode = "digital"
p1_buttons = []
p1_left_x = 0
p1_left_y = 0
p1_right_x = 0
p1_right_y = 0
p1_trigger_left = 0
p1_trigger_right = 0
p2_connected = false
p2_mode = "digital"
p2_buttons = []
p2_left_x = 0
p2_left_y = 0
p2_right_x = 0
p2_right_y = 0
p2_trigger_left = 0
p2_trigger_right = 0

[[vblank]]
repeat = 8
p1_connected = true
p1_mode = "digital"
p1_buttons = ["a"]
p1_left_x = 0
p1_left_y = 0
p1_right_x = 0
p1_right_y = 0
p1_trigger_left = 0
p1_trigger_right = 0
p2_connected = false
p2_mode = "digital"
p2_buttons = []
p2_left_x = 0
p2_left_y = 0
p2_right_x = 0
p2_right_y = 0
p2_trigger_left = 0
p2_trigger_right = 0

[[vblank]]
repeat = 270
p1_connected = true
p1_mode = "digital"
p1_buttons = []
p1_left_x = 0
p1_left_y = 0
p1_right_x = 0
p1_right_y = 0
p1_trigger_left = 0
p1_trigger_right = 0
p2_connected = false
p2_mode = "digital"
p2_buttons = []
p2_left_x = 0
p2_left_y = 0
p2_right_x = 0
p2_right_y = 0
p2_trigger_left = 0
p2_trigger_right = 0

[[vblank]]
repeat = 9
p1_connected = true
p1_mode = "digital"
p1_buttons = ["a"]
p1_left_x = 0
p1_left_y = 0
p1_right_x = 0
p1_right_y = 0
p1_trigger_left = 0
p1_trigger_right = 0
p2_connected = false
p2_mode = "digital"
p2_buttons = []
p2_left_x = 0
p2_left_y = 0
p2_right_x = 0
p2_right_y = 0
p2_trigger_left = 0
p2_trigger_right = 0

[[vblank]]
repeat = 125
p1_connected = true
p1_mode = "digital"
p1_buttons = []
p1_left_x = 0
p1_left_y = 0
p1_right_x = 0
p1_right_y = 0
p1_trigger_left = 0
p1_trigger_right = 0
p2_connected = false
p2_mode = "digital"
p2_buttons = []
p2_left_x = 0
p2_left_y = 0
p2_right_x = 0
p2_right_y = 0
p2_trigger_left = 0
p2_trigger_right = 0

[[vblank]]
repeat = 6
p1_connected = true
p1_mode = "digital"
p1_buttons = ["a"]
p1_left_x = 0
p1_left_y = 0
p1_right_x = 0
p1_right_y = 0
p1_trigger_left = 0
p1_trigger_right = 0
p2_connected = false
p2_mode = "digital"
p2_buttons = []
p2_left_x = 0
p2_left_y = 0
p2_right_x = 0
p2_right_y = 0
p2_trigger_left = 0
p2_trigger_right = 0

[[vblank]]
repeat = 78
p1_connected = true
p1_mode = "digital"
p1_buttons = []
p1_left_x = 0
p1_left_y = 0
p1_right_x = 0
p1_right_y = 0
p1_trigger_left = 0
p1_trigger_right = 0
p2_connected = false
p2_mode = "digital"
p2_buttons = []
p2_left_x = 0
p2_left_y = 0
p2_right_x = 0
p2_right_y = 0
p2_trigger_left = 0
p2_trigger_right = 0
