#!/usr/bin/env python3
"""Generate docs/OPERATION_CATALOG.md from the bundled opcode table and operand schemas."""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from battle_event_codec import COMPARISON_DESCRIPTIONS, FIELD_SIZES, SPECS, check_table, load_opcode_table

OUTPUT = Path(__file__).resolve().parents[1] / "docs" / "OPERATION_CATALOG.md"

KIND_TEXT = {
    "u8": "u8 immediate",
    "s8": "s8 immediate",
    "u16": "u16 immediate",
    "v15": "v15 (bit 15 set: immediate `& 0x7FFF`; clear: variable offset)",
    "typed": "u16, immediate or variable by its type-mask bit",
    "dest": "u16 direct variable offset",
    "var": "u16 variable offset (always a variable)",
    "label": "u16 bytecode offset (relocated label)",
    "mask": "type mask byte",
    "entity": "u8 Event entity ID",
    "packed": "u8 packed entry: bits 0..4 entry, bits 5..7 slot state",
}

SUGAR = {
    0x00: "stop;",
    0x01: "goto label;",
    0x02: "if (!(left OP right)) goto label;",
    0x06: "x = value;",
    0x07: "x = true;",
    0x08: "x = false;",
    0x09: "x += value;",
    0x0A: "x -= value;",
    0x0B: "x |= value;",
    0x0C: "x &= ~value;",
    0x0D: "x++;",
    0x0E: "x--;",
    0x0F: "x &= value;",
    0x11: "x ^= value;",
    0x12: "x <<= count_variable;",
    0x13: "x >>= count_variable;",
    0x14: "x = random();",
    0x15: "x = random(upper_bound);",
    0x16: "x *= value;",
    0x17: "x /= value;",
}


def function_form(spec) -> str:
    args = []
    for operand in spec.operands:
        if operand.kind == "mask":
            continue
        if operand.kind == "packed":
            args.extend(("entry", "slot_state"))
        elif operand.name == "reserved":
            args.append("reserved=0")
        else:
            args.append(operand.name)
    if spec.mask_operand is not None and spec.opcode != 0x02:
        args.append("reserved_flags=0")
    return f"{spec.qualified}({', '.join(args)});"


def layout(spec) -> list[str]:
    rows = ["| Offset | Size | Field | Encoding |", "|---:|---:|---|---|", "| `+0` | 1 | opcode | `" + f"{spec.opcode:02X}" + "` |"]
    offset = 1
    for operand in spec.operands:
        size = FIELD_SIZES[operand.kind]
        text = KIND_TEXT[operand.kind]
        if operand.bit:
            text += f"; type bit `0x{operand.bit:02X}`"
        if operand.kind == "mask" and spec.opcode == 0x02:
            text = "bit `0x80` left immediate, `0x40` right immediate, low nibble comparison selector"
        rows.append(f"| `+{offset}` | {size} | `{operand.name}` | {text} |")
        offset += size
    return rows


def main() -> int:
    check_table()
    table = load_opcode_table()["opcodes"]
    by_namespace = defaultdict(list)
    for spec in SPECS.values():
        by_namespace[spec.namespace].append(spec)
    lines = [
        "# Battle Event Operation Catalog",
        "",
        "Generated by `tools/build_dsl_documentation.py` from",
        "`tools/battle_event_opcode_table.json` (dispatch names, sizes, handlers and",
        "behavior from the Battle documentation) and the operand schemas in",
        "`tools/battle_event_codec.py`. Do not edit by hand.",
        "",
        f"The dispatch table covers `0x00..0x4B` ({len(SPECS)} opcodes). Values above",
        "`0x4B` skip handler dispatch and are never rendered as instructions.",
        "",
        "## Summary",
        "",
        "| Op | Bytes | XGS operation | Handler |",
        "|---:|---:|---|---|",
    ]
    for spec in SPECS.values():
        record = table[f"{spec.opcode:02X}"]
        lines.append(f"| `{spec.opcode:02X}` | {spec.size} | `{spec.qualified}` | `{record['handler']}` |")
    lines += ["", "## Comparison Selectors", "",
              "`flow.jump_unless` (`02`) stores the comparison in the low nibble of its",
              "mask byte. Bits `0x20` and `0x10` are not read and appear as",
              "`reserved_flags` when set.", "",
              "| Selector | XGS condition | Test |", "|---:|---|---|"]
    spellings = {0: "a == b", 1: "a != b", 2: "a > b", 3: "a < b", 4: "a >= b", 5: "a <= b", 6: "a & b",
                 7: "compare(a, b, 7)", 8: "a || b", 9: "mask_contains(a, b)", 10: "mask_lacks(a, b)"}
    for selector, description in COMPARISON_DESCRIPTIONS.items():
        spelling = spellings.get(selector, f"compare(a, b, {selector})")
        cell = lambda text: text.replace("|", "\\|")  # noqa: E731
        lines.append(f"| `{selector:X}` | `{cell(spelling)}` | {cell(description)} |")
    for namespace in sorted(by_namespace):
        lines += ["", f"## `{namespace}`"]
        for spec in by_namespace[namespace]:
            record = table[f"{spec.opcode:02X}"]
            lines += ["", f"### `{spec.opcode:02X}` `{spec.qualified}`", "",
                      f"- Handler: `{record['handler']}` `{record['function']}`",
                      f"- Size: {record['bytes']}" + (" (ends the block)" if spec.terminal else ""),
                      f"- Effect: {spec.summary}",
                      f"- Documented behavior: {record['behavior']}",
                      ("- Function form: none; write the `if` statement below" if spec.opcode == 0x02
                       else f"- Function form: `{function_form(spec)}`")]
            if spec.opcode in SUGAR:
                lines.append(f"- Concise form: `{SUGAR[spec.opcode]}`")
            lines += [""] + layout(spec)
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
